version: '3.8'

services:
  web:
    build: ./gitspy
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./gitspy/:/gitspy
    ports:
      - 8000:8000
    env_file:
      - ./gitspy/gitspy/.env